// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"], // Usa el Pooler (puerto 6543) para las consultas de la app
    directUrl: process.env["DIRECT_URL"] // Conexión directa (puerto 5432) para migraciones
    
  },
});